### ISSUE TITLE
Note playing is non-stop if key is pressed briefly

### ISSUE THREAD

**Issue by Lchikar** [lrathoni/Lullaby-for-a-fish#12]
On the latest master branch version of the project, when you press a note key (y, u, i, o, p) the note is playing continuously until another note (or the same) is pressed again.
This issue does not occur when you press for more than 1 sec the note key.

**Comment by piptouque** [comment]
Thanks, I'll check it out!

**Comment by piptouque** [comment]
Just fixed it (hopefully), you can check that notes are cancelled properly in the linked pull request #13 .
